### ISSUE TITLE
[Bug] Probably memory leak while publishing ROS topic continuously

### ISSUE THREAD

**Issue by evshary** [eclipse-zenoh/zenoh-plugin-dds#115]
### Describe the bug

I ran the Autoware with AWSIM simulator, which they are in different domains and connected to each other with zenoh-bridge-dds.

```
 (domain 1)       (domain 1)              (domain 2)        (domain 2)
    AWSIM ---- (zenoh-bridge-dds) --- (zenoh-bridge-dds) --- Autoware
```

I found that memory usage was continuously increasing, and the zenoh-bridge-dds would crash.
Here is the video while memory usage increased

https://user-images.githubusercontent.com/456210/218941092-a8bfee19-d52d-40ec-9cca-08b681b25142.mp4

I guess the issue would happen while publishing data continuously.
To simplify the scenario, I ran two ROS nodes with zenoh-bridge-dds connected.
One of the nodes received image data from the camera and published it to another node.
I found that the same issue still happened.

### To reproduce

1. Open 1st terminal and publish image from camera: `ROS_DOMAIN_ID=1 ros2 run image_tools cam2image`
2. Open 2nd terminal and subscribe image: `ROS_DOMAIN_ID=2 ros2 run image_tools showimage`
3. Open 3rd terminal and run the bridge: `./target/release/zenoh-bridge-dds -d 1`
4. Open 4th terminal and run the bridge: `./target/release/zenoh-bridge-dds -d 2`

Then using htop to observe the zenoh-bridge-dds memory usage.

### System info

- Platform: Ubuntu 20.04
- ROS2 version: galactic
- zenoh-bridge-dds version: f94ae615874225f4896f3350c78dab007d12c21e

**Comment by JEnoch** [comment]
After analysis, the leak occurs when a data is routed from Zenoh to DDS, calling `dds_writecdr()`.
The bug is in [cyclocut](https://github.com/kydos/cyclocut). Fix to come soon.
