### ISSUE TITLE
[Bug] minor spelling mistakes

### ISSUE THREAD

**Issue by hwoithe** [eclipse-zenoh/zenoh-plugin-dds#138]
### Describe the bug

Minor spelling mistakes in help, error, and debug messages.

### To reproduce

While using `zenoh-bridge-dds` I discovered a few minor spelling mistakes. Please see below.

```
zenoh_bridge_dds --help | grep environement
```

environement -> environment
https://github.com/eclipse-zenoh/zenoh-plugin-dds/blob/eefc16f0997da6b6515c09adfba3fb1b26147eff/zenoh-bridge-dds/src/main.rs#L100

todeclare -> to declare
https://github.com/eclipse-zenoh/zenoh-plugin-dds/blob/eefc16f0997da6b6515c09adfba3fb1b26147eff/zenoh-plugin-dds/src/lib.rs#L180

forarding -> forwarding
https://github.com/eclipse-zenoh/zenoh-plugin-dds/blob/eefc16f0997da6b6515c09adfba3fb1b26147eff/zenoh-plugin-dds/src/route_zenoh_dds.rs#L138

### System info

System Info
- Platform: Ubuntu 22.04.2
- CPU: Intel(R) Core(TM) i9-7920X CPU @ 2.90GHz
- zenoh-plugin-dds: commit eefc16f0

**Comment by JEnoch** [comment]
Thanks for reporting this! Fixed now.
