### ISSUE TITLE
[ Configuration ] Cannot stream pointcloud over Wifi

### ISSUE THREAD

**Issue by GiovanniBalestrieri** [eclipse-zenoh/zenoh-plugin-dds#153]
### Describe the issue

I'm encountering an issue when attempting to stream pointcloud data from a host connected to a wired network to another connected over Wi-Fi. The setup involves a Zenoh Router and three Zenoh Bridges. The configuration functions correctly when all hosts are connected to the wired network.

**Test 1 - Successful** 

In this test, Hosts A, B, and C are all connected to the Ubuntu Router using Ethernet cables. I can visualize, on Host C, the pointcloud in RViz2. 
![zenoh_lan_case_wifi_issue](https://github.com/eclipse-zenoh/zenoh-plugin-dds/assets/1172783/ea762929-2bfb-483d-b124-0506f0288df6)

**Test 2 - Failed**
In this test, Hosts A and B are connected to the Ubuntu Router using Ethernet cables, while Host C is connected over Wi-Fi.
![zenoh_wifi_issue](https://github.com/eclipse-zenoh/zenoh-plugin-dds/assets/1172783/e63d8d3d-cd9f-494c-b257-d6bda6985be8)

The problem arises when running the zenoh-bridge-dds command as the connection freezes.

### To reproduce

I am using the following configuration in both cases. The wired case works well, but the wireless doesn't.

1. Router: 
`zenohd`

2. Host A:
`export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp`
`zenoh-bridge-dds -m client -e tcp/192.168.0.1:7447 --no-multicast-scouting`
`ros2 launch ros_package_x publish_string_topic.launch.py`

2. Host B:
`export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp`
`zenoh-bridge-dds -m client -e tcp/192.168.0.1:7447 --no-multicast-scouting`
`ros2 launch ros_package_x publish_pointcloud_topic.launch.py`

2. Host C
`export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp`
`zenoh-bridge-dds -m client -e tcp/192.168.0.1:7447 --no-multicast-scouting`
`ros2 run rviz2 rviz2`

### System info

- Router
Ubuntu 20.04 
IP: 192.168.0.1
zenohd v0.10.0-rc built with rustc 1.72.0
zenoh command:
`zenohd `

- Host A
Ubuntu 20.04
IP: 192.168.0.2
Ros2 Foxy and CycloneDDS RMW
zenohd v0.10.0-rc built with rustc 1.72.0
zenoh command:
`zenoh-bridge-dds -m client -e tcp/192.168.0.1:7447 --no-multicast-scouting`

- Host B
Ubuntu 20.04
IP: 192.168.0.3
Ros2 Foxy and CycloneDDS RMW
zenohd v0.10.0-rc built with rustc 1.72.0
zenoh command:
`zenoh-bridge-dds -m client -e tcp/192.168.0.1:7447 --no-multicast-scouting`

- Host C - Wired
Ubuntu 20.04
IP: 192.168.0.5
Ros2 Foxy and CycloneDDS RMW
zenohd v0.10.0-rc built with rustc 1.72.0
zenoh command:
`zenoh-bridge-dds -m client -e tcp/192.168.0.1:7447 --no-multicast-scouting`

- Host C - Wifi
Ubuntu 20.04
IP: 192.168.0.226
Ros2 Foxy and CycloneDDS RMW
zenohd v0.10.0-rc built with rustc 1.72.0
zenoh command:
`zenoh-bridge-dds -m client -e tcp/192.168.0.1:7447 --no-multicast-scouting`

I've reviewed previous issues and tutorials but haven't found a suitable configuration for this wireless case.

PS: The label Bug has been added automatically and I cannot modify it. It's just an issue with my configuration.

**Comment by kydos** [comment]
Hello @GiovanniBalestrieri, looking at the configuration above the issues seems to be that you are always passing the same locator: `tcp/192.168.0.1:7447`. This would work as a point of RDV if you would enable the gossip discovery (see config example on zenoh distro). The other approach is to pass the locators of the other machines. 

HTH.

**Comment by GiovanniBalestrieri** [comment]
Hi @kydos, I am happy to modify the approach. I took a bit of time to further study the documentation. ESpecially [this](https://conferences2.sigcomm.org/acm-icn/2022/assets/zenoh-4-Zenoh-and-Zenoh-Flow-Hands-on-e8cbd760e0b88b74417fb1c14d1d373b5ce2a094bc29b5f1a0bfd8e52030c151.pdf) pdf and the help section of zenohd 

```
-l, --listen <ENDPOINT>...
A locator on which this router will listen for
incoming sessions. Repeat this option to open
several listeners.
-e, --connect <ENDPOINT>...
A peer locator this router will try to
connect to. Repeat this option to connect to
several peers.
```


> _The other approach is to pass the locators of the other machines._

**Attempt I Wired setup**
I tried passing to Host A and B the locator each other using
- Router - 192.168.0.1
```  zenohd```

- Host A - IP: 192.168.0.2

> zenoh-bridge-dds -m peer -e tcp/192.168.0.1:7447 -l tcp/192.168.0.3:7447
> [2023-10-17T12:40:14Z INFO  zenoh_bridge_dds] zenoh-bridge-dds v0.10.0-rc built with rustc 1.72.1 (d5c2e9c34 2023-09-13)
> [2023-10-17T12:40:14Z INFO  zenoh::net::runtime] Using PID: c944286c0f310276499cf9908db65b89
> [2023-10-17T12:40:14Z ERROR zenoh::net::runtime::orchestrator] Unable to open listener tcp/192.168.0.3:7447: Can not create a new TCP listener bound to tcp/192.168.0.3:7447: [192.168.0.3:7447: Cannot assign requested address (os error 99) at /cargo/registry/src/index.crates.io-6f17d22bba15001f/zenoh-link-tcp-0.10.0-rc/src/unicast.rs:245.] at /cargo/registry/src/index.crates.io-6f17d22bba15001f/zenoh-link-tcp-0.10.0-rc/src/unicast.rs:333.
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Can not create a new TCP listener bound to tcp/192.168.0.3:7447: [192.168.0.3:7447: Cannot assign requested address (os error 99) at /cargo/registry/src/index.crates.io-6f17d22bba15001f/zenoh-link-tcp-0.10.0-rc/src/unicast.rs:245.] at /cargo/registry/src/index.crates.io-6f17d22bba15001f/zenoh-link-tcp-0.10.0-rc/src/unicast.rs:333.', zenoh-bridge-dds/src/main.rs:247:62
> stack backtrace:
>    0:       0x558887641c - <unknown>
>    1:       0x558869c0b0 - <unknown>
>    2:       0x558884b740 - <unknown>
>    3:       0x5588877484 - <unknown>
>    4:       0x5588877090 - <unknown>
>    5:       0x5588877fa4 - <unknown>
>    6:       0x5588877af0 - <unknown>
>    7:       0x5588877a64 - <unknown>
>    8:       0x5588877a58 - <unknown>
>    9:       0x558857e9ec - <unknown>
>   10:       0x558857ecfc - <unknown>
>   11:       0x55886274e4 - <unknown>
>   12:       0x558861ca6c - <unknown>
>   13:       0x55885c7ee0 - <unknown>
>   14:       0x5588627c9c - <unknown>
>   15:       0x7fa54c2e10 - __libc_start_main
>   16:       0x55885afda4 - <unknown>
> Aborted


- Host B - IP: 192.168.0.3
   zenoh-bridge-dds -m peer -e tcp/192.168.0.1:7447 -l tcp/192.168.0.2:7447
   Same error message as above

Why am I getting this error? It will help me understand what is happening under the hood. 

**Attempt II Wired setup**
Using client mode 

- Router - 192.168.0.1
```  zenohd```

- Host A - IP: 192.168.0.2
`zenoh-bridge-dds -m client -e tcp/192.168.0.1:7447 -l tcp/192.168.0.3:7447 -l tcp/192.168.0.5:7447`

- Host B - IP: 192.168.0.3
`zenoh-bridge-dds -m client -e tcp/192.168.0.1:7447 -l tcp/192.168.0.2:7447 -l tcp/192.168.0.5:7447`

- Host C - IP: 192.168.0.5
`zenoh-bridge-dds -m client -e tcp/192.168.0.1:7447 -l tcp/192.168.0.2:7447 -l tcp/192.168.0.3:7447`

No error  messages. 
Opened Rviz2 on host C, one poincloud message got through then the connection to Host B, the one publishing the pointcloud, dropped for a few seconds. 


**Attempt III Wired setup --no-multicast-scouting**
Using client mode 

- Router - 192.168.0.1
```  zenohd```

- Host A - IP: 192.168.0.2
`zenoh-bridge-dds -m client -e tcp/192.168.0.1:7447 -l tcp/192.168.0.3:7447 -l tcp/192.168.0.5:7447` --no-multicast-scouting

- Host B - IP: 192.168.0.3
`zenoh-bridge-dds -m client -e tcp/192.168.0.1:7447 -l tcp/192.168.0.2:7447 -l tcp/192.168.0.5:7447` --no-multicast-scouting

- Host C - IP: 192.168.0.5
`zenoh-bridge-dds -m client -e tcp/192.168.0.1:7447 -l tcp/192.168.0.2:7447 -l tcp/192.168.0.3:7447  --no-multicast-scouting`

No error  messages. 
Opened Rviz2 on host C and got 18 messages per second. Ok.

**Attempt IV Wireless setup --no-multicast-scouting**
Moving to the wireless case. 

- Router - 192.168.0.1
```  zenohd```

- Host A - IP: 192.168.0.2
`zenoh-bridge-dds -m client -e tcp/192.168.0.1:7447 -l tcp/192.168.0.3:7447 -l tcp/192.168.0.5:7447` --no-multicast-scouting

- Host B - IP: 192.168.0.3
`zenoh-bridge-dds -m client -e tcp/192.168.0.1:7447 -l tcp/192.168.0.2:7447 -l tcp/192.168.0.5:7447` --no-multicast-scouting

- Host C - IP: 192.168.0.5
`zenoh-bridge-dds -m client -e tcp/192.168.0.1:7447 -l tcp/192.168.0.2:7447 -l tcp/192.168.0.3:7447  --no-multicast-scouting`

**Comment by GiovanniBalestrieri** [comment]
Now reading these resources to better understand the situation
- https://zenoh.io/docs/getting-started/deployment/
- https://www.youtube.com/watch?v=ahO4kT_Zg7s&t=1577s

**Comment by JEnoch** [comment]
Hi @GiovanniBalestrieri ,

We recently developed a new Zenoh bridge for ROS 2:  https://github.com/eclipse-zenoh/zenoh-plugin-ros2dds
I recommand you switch to this one as it better integrates with ROS 2 and brings these benefits:

- Better integration of the ROS graph (all ROS topics/services/actions can be seen across bridges)
- Better support of ROS toolings (ros2 CLI, rviz2...)
- Configuration of a ROS namespace on the bridge (instead of on each ROS Node)
- Services and Action as Zenoh Queryables with more efficiency and scalability that RPC over DDS
- Even more compact discovery information between the bridges (not forwarding all ros_discovery_info messages as such)

RViz and the ros2 commands are working smoothly with it, as I showed in a demo at ROSCon 2023.

Still, publishing at high rate larges data such as pointcloud might be problematic over WiFi where bandwidth might be limited and messages loss could occur.
My advise is also to lower the frequency of republication by the bridge for your pointcloud topic using the [`pub_max_frequency`](https://github.com/eclipse-zenoh/zenoh-plugin-ros2dds/blob/a485c63840b2be5832eb0ffabc98e75874b79943/DEFAULT_CONFIG.json5#L81) configuration.

I'm closing this issue since I hope you'll test the new bridge with this config. If you still have troubles, please open a new issue in [its repo](https://github.com/eclipse-zenoh/zenoh-plugin-ros2dds/issues).
