### ISSUE TITLE
Docker build error

### ISSUE THREAD

**Issue by Yingliangzhe** [eclipse-zenoh/zenoh-plugin-dds#29]
I have downloaded the zenoh plugin dds on my PC. I could sucessfully build the rust binary unter the target/release, although there was also not that smooth. 
But I want to use it as a docker container. 
As I ran the command `docker build -t zenoh-bridge:latest /zenoh-plugin-dds/`, it failed at step 6/18, with the following error message:
`error: could not compile zplugin-dds                                                                         
Caused by:
  process didn't exit successfully: rustc --crate-name dzd --edition=2018 src/bin/zenoh-bridge-dds.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C panic=abort -C lto=fat -C codegen-units=1 -C metadata=ba6255499f3b3893 -C extra-filename=-ba6255499f3b3893 --out-dir /usr/src/zenoh-plugin-dds/target/release/deps -L dependency=/usr/src/zenoh-plugin-dds/target/release/deps --extern async_std=/usr/src/zenoh-plugin-dds/target/release/deps/libasync_std-971771c819c3d6ae.rlib --extern async_trait=/usr/src/zenoh-plugin-dds/target/release/deps/libasync_trait-d330024b777d927b.so --extern clap=/usr/src/zenoh-plugin-dds/target/release/deps/libclap-f130171fc73c7873.rlib --extern cyclors=/usr/src/zenoh-plugin-dds/target/release/deps/libcyclors-5c0dc288e3ea32a3.rlib --extern env_logger=/usr/src/zenoh-plugin-dds/target/release/deps/libenv_logger-065286da14da1e1f.rlib --extern futures=/usr/src/zenoh-plugin-dds/target/release/deps/libfutures-3257bf31cb9dd6ef.rlib --extern libc=/usr/src/zenoh-plugin-dds/target/release/deps/liblibc-82fc623194b48829.rlib --extern log=/usr/src/zenoh-plugin-dds/target/release/deps/liblog-06380b60399c477a.rlib --extern regex=/usr/src/zenoh-plugin-dds/target/release/deps/libregex-1ba1495b2025cb1f.rlib --extern zenoh=/usr/src/zenoh-plugin-dds/target/release/deps/libzenoh-6dc48809802b17c2.rlib --extern zplugin_dds=/usr/src/zenoh-plugin-dds/target/release/deps/libzplugin_dds-064595951d1906a9.rlib -L /usr/local/lib -L native=/usr/src/zenoh-plugin-dds/target/release/build/cyclors-3432522568f8014c/out/cyclonedds-build/lib -L native=/usr/src/zenoh-plugin-dds/target/release/build/cyclors-3432522568f8014c/out/cyclocut-build/lib -L native=/usr/src/zenoh-plugin-dds/target/release/build/ring-3baaa555570ba30c/out (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...
error: failed to compile zplugin-dds v0.5.0-beta.2 (/usr/src/zenoh-plugin-dds), intermediate artifacts can be found at /usr/src/zenoh-plugin-dds/target`

Could someone tell me, how to fix this error? 

My OS and architecture is:
Linux my-server 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by JEnoch** [comment]
The message is not really explicit: the `rustc` compilation command seems to have been killed, but without obvious reason...

I just tried the same command as you on my MacOS, and the build succeeds in 8 steps:
```log
hao:~/tmp$ docker build -t zenoh-bridge:latest ./zenoh-plugin-dds/
[+] Building 2369.6s (21/21) FINISHED
 => [internal] load build definition from Dockerfile                                                                                   0.0s
 => => transferring dockerfile: 37B                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                      0.0s
 => => transferring context: 35B                                                                                                       0.0s
 => [internal] load metadata for docker.io/library/debian:buster-slim                                                                  0.0s
 => [internal] load metadata for docker.io/library/rust:slim                                                                           1.7s
 => [auth] library/rust:pull token for registry-1.docker.io                                                                            0.0s
 => [internal] load build context                                                                                                      0.0s
 => => transferring context: 677B                                                                                                      0.0s
 => [builder 1/6] FROM docker.io/library/rust:slim@sha256:14f30a50809805fec8b6dd4ad31ebb68f2a71e12ffd324b50ec8d8992449b374             0.0s
 => [stage-1 1/8] FROM docker.io/library/debian:buster-slim                                                                            0.0s
 => CACHED [builder 2/6] WORKDIR /usr/src/zenoh-plugin-dds                                                                             0.0s
 => CACHED [builder 3/6] RUN mkdir /usr/share/man/man1/                                                                                0.0s
 => CACHED [builder 4/6] RUN apt-get update && apt-get -y install g++ cmake libssl-dev openjdk-11-jdk-headless maven git clang         0.0s
 => CACHED [builder 5/6] COPY . .                                                                                                      0.0s
 => [builder 6/6] RUN cargo install --path .                                                                                        2365.5s
 => CACHED [stage-1 2/8] RUN apt-get update && apt-get install -y libssl1.1 && rm -rf /var/lib/apt/lists/*                             0.0s
 => [stage-1 3/8] COPY --from=builder /usr/local/cargo/bin/zenoh-bridge-dds /usr/local/bin/zenoh-bridge-dds                            0.1s
 => [stage-1 4/8] RUN ldconfig -v                                                                                                      0.4s
 => [stage-1 5/8] RUN echo '#!/bin/bash' > /entrypoint.sh                                                                              0.4s
 => [stage-1 6/8] RUN echo 'echo " * Starting: zenoh-bridge-dds $*"' >> /entrypoint.sh                                                 0.4s
 => [stage-1 7/8] RUN echo 'exec zenoh-bridge-dds $*' >> /entrypoint.sh                                                                0.4s
 => [stage-1 8/8] RUN chmod +x /entrypoint.sh                                                                                          0.4s
 => exporting to image                                                                                                                 0.1s
 => => exporting layers                                                                                                                0.1s
 => => writing image sha256:811217fc124edb53098d83bf8dfa27a58ef53d5d99774e38659df46af8bca231                                           0.0s
 => => naming to docker.io/library/zenoh-bridge:latest                                                                                 0.0s
```

So I wonder why you get 18 steps (or is it a typo ?)

An explanation could be a lack of resources (memory? disk?) leading Docker or the containerized OS to kill the build.  
A Rust build can take a lot of resources (+3Gb on disk). However, the final image is fortunately stripped down to ~80Mb.  
FYI my Docker engine is configured with 4Gb memory, 2Gb swap and 32Gb disk image.
