### ISSUE TITLE
Compatibility between opendds and cyclonedds

### ISSUE THREAD

**Issue by Yingliangzhe** [eclipse-zenoh/zenoh-plugin-dds#30]
Hello everyone,
I have a question about the compartibility of opendds as mentioned in title.
If I would like to write a publisher in opendds and a subscriber in cyclone. Would it be possible, that the subscriber receives the messages from the publisher, which is writen in opendds? Have you already tested the compartibility? 
Thank you!

**Comment by JEnoch** [comment]
Hi @Yingliangzhe ,

Both OpenDDS and CycloneDDS implement the standard OMG DDSI protocol, so I'm pretty sure they can interoperate, at least without DDS security.
I don't know in the detail which compatibility tests have been performed (with or without DDS security) or if there is any gotcha. But feel free to ask the CycloneDDS team posting an issue in https://github.com/eclipse-cyclonedds/cyclonedds/issues.
