### ISSUE TITLE
zenoh-plugin-dds docker port

### ISSUE THREAD

**Issue by Yingliangzhe** [eclipse-zenoh/zenoh-plugin-dds#32]
I am using the zenoh plugin dds inside a docker container. 
As I ran `docker run -e RUST_LOG=debug  --name zenoh-bridge -p 7447:7447/tcp zenoh-bridge`, the zenohd can not  be reached at the port 7447, but at another port `zenohd can be reached on tcp/172.17.0.2:35065`. 
But the `docker ps` shows me:
`7447/udp, 0.0.0.0:7447->7447/tcp, :::7447->7447/tcp   zenoh-bridge`. The docker command should be right, but why the port 7447 is not opened?

**Comment by JEnoch** [comment]
Hi @Yingliangzhe ,

The log is misleading: the bridge for DDS is not a zenoh router (`zenohd`), but a regular zenoh application that can be configured in `peer` or `client` mode (see the zenoh [deployment units](https://zenoh.io/docs/getting-started/key-concepts/#deployment-units)).
As such, the bridge doesn't by default listen for incoming TCP connections on port 7447. Only the `zenohd` router does that.
However, you can configure the bridge to listen for incoming TCP connections on the port you want (including 7447) using the  `-l` option. For instance with your container:
```bash
docker run -e RUST_LOG=debug --name zenoh-bridge -p 7447:7447/tcp zenoh-bridge -l tcp/0.0.0.0:7447
```

I created eclipse-zenoh/zenoh#93 to fix the misleading log.
