### ISSUE TITLE
DDS data routing and forwarding through zenoh

### ISSUE THREAD

**Issue by kydos** [eclipse-zenoh/zenoh-plugin-dds#6]
The aim of this first phase is to provide the ability to dynamically discover DDS entities and then create on the fly the required matching entities on DDS side and some associated entities in zenoh to allow for data forwarding.

**Comment by akila-ganlath** [comment]
@kydos is there a listing/documentation of DDS QoS that is currently and planned to be supported across the Zenoh router?

**Comment by JEnoch** [comment]
Outdated ticket.
